# Generated by Django 2.1.4 on 2019-02-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pineapp', '0003_auto_20190216_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
